INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (1, 'Shou Mei', 'Thé Oolong', 17, 17);
INSERT INTO PRODUCT(id, name, category, price, buyPrice) VALUES (2, 'Marocain', 'Thé vert', 12, 12);
INSERT INTO PRODUCT(id, name, category, price, buyPrice)  VALUES (3, 'Légende Tibétaine', 'Thé noir', 14, 14);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (4, 'Darjeeling', 'Thé noir', 5, 3);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (5, 'Earl Grey', 'Thé noir', 6, 4);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (6, 'English Breakfast', 'Thé noir', 4, 2);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (7, 'Lapsang Souchong', 'Thé noir', 7, 5);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (8, 'Keemun', 'Thé noir', 5, 3);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (9, 'Ceylan', 'Thé noir', 6, 4);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (10, 'Assam', 'Thé noir', 5, 4);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (11, 'Sencha', 'Thé vert', 4, 2);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (12, 'Matcha', 'Thé vert', 9, 7);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (13, 'Gunpowder', 'Thé vert', 3, 2);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (14, 'Dragonwell (Longjing)', 'Thé vert', 8, 6);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (15, 'Gyokuro', 'Thé vert', 11, 9);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (16, 'Jasmine Dragon Pearls', 'Thé vert', 10, 8);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (17, 'Tie Guan Yin (Iron Goddess of Mercy)', 'Thé oolong', 14, 12);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (18, 'Da Hong Pao (Big Red Robe)', 'Thé oolong', 18, 15);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (19, 'Formosa (Oolong de Taïwan)', 'Thé oolong', 16, 13);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (20, 'Oriental Beauty', 'Thé oolong', 22, 19);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (21, 'Ti Kuan Yin (Tie Guan Yin)', 'Thé oolong', 19, 16);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (22, 'Silver Needle (Aiguilles d''Argent)', 'Thé blanc', 25, 22);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (23, 'Jun Shan Yin Zhen (Aiguilles d''Argent de Jun Shan)', 'Thé blanc', 28, 25);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (24, 'Sheng Puerh (Puerh cru)', 'Thé Puerh', 32, 29);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (25, 'Rooibos nature', 'Infusion', 9, 7);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (26, 'Camomille', 'Infusion', 8, 6);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (27, 'Thé à la vanille', 'Thé aromatisé', 12, 10);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (28, 'Masala Chai', 'Thé aromatisé', 11, 9);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (29, 'Thé à la framboise', 'Thé aromatisé', 13, 11);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (30, 'Russian Caravan', 'Thé fumé', 14, 12);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (31, 'Thé au jasmin', 'Thé vert aromatisé', 15, 13);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (32, 'Mo Gan Huang Ya (Pousse Jaune de Mo Gan)', 'Thé jaune', 16, 14);
INSERT INTO PRODUCT (id, name, category, price, buyPrice) VALUES (33, 'Thé à la pêche', 'Thé aromatisé', 17, 15);
